### ISSUE TITLE
collect2.exe: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by cbcy1234** [jadonmmiller/ESP32-8048S070-LVGL-Demo#1]
c:/users/administrator/.platformio/packages/toolchain-xtensa-esp32s3@8.4.0+2021r2-patch5/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio\build\sunton_s3\src\main.cpp.o:(.literal._Z5setupv+0x40): undefined reference to `lv_demo_widgets'
c:/users/administrator/.platformio/packages/toolchain-xtensa-esp32s3@8.4.0+2021r2-patch5/bin/../lib/gcc/xtensa-esp32s3-elf/8.4.0/../../../../xtensa-esp32s3-elf/bin/ld.exe: .pio\build\sunton_s3\src\main.cpp.o: in function `setup()':
C:\Users\Administrator\Documents\PlatformIO\Projects\ESP32-8048S070-LVGL-Demo-main/src/main.cpp:110: undefined reference to `lv_demo_widgets'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\sunton_s3\firmware.elf] Error 1

May I ask how to solve it? Thank you!

**Comment by jadonmmiller** [comment]
Good morning!

The compiler can't find the LVGL demos source file. I'm sure there's a way to make the compiler include that, but I can't figure out how. So, please copy the ".pio\libdeps\sunton_s3\lvgl\demos" folder to ".pio\libdeps\sunton_s3\lvgl\src".

That should fix your "undefined reference" error, and I've added a note to the read-me for clarification on that.

Sorry for the issues!
